backend:
  replicaCount: 1
  image:
    repository: todo-backend
    tag: latest
    pullPolicy: Never # For Minikube local dev
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

frontend:
  replicaCount: 1
  image:
    repository: todo-frontend
    tag: latest
    pullPolicy: Never # For Minikube local dev
  service:
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 30080
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

global:
  env:
    # Non-sensitive config
    BACKEND_HOST: "todo-backend"
